language: java
services:
- mongodb
jdk:
- oraclejdk8
after_success:
- mkdir -p target/upload
- cp target/*.jar target/upload
deploy:
  provider: s3
  access_key_id: $S3_KEY
  secret_access_key: $S3_SECRET
  bucket: tilosdeploy
  local_dir: target/upload
  acl: public_read
  on:
    repo: tilosradio/service-ttt
