language: java
jdk:
- oraclejdk8
after_success:
- mkdir -p target/upload
- cp target/*.jar target/upload/service-ttt.jar
deploy:
  provider: s3
  access_key_id: $S3_KEY
  secret_access_key: $S3_SECRET
  bucket: tilosdeploy
  acl: public_read
  local_dir: target/upload
  skip_cleanup: true
  on:
    repo: tilosradio/service-ttt
